### ISSUE TITLE
Can't start a fabric server with newest version of chemlib

### ISSUE THREAD

**Issue by Han3422** [TechnoVisionDev/ChemLib#3]
Hello, I was making a minecraft server with fabric but seems like chemlib has a problem. I already researched in google still can't get to solve the issue. I tried starting the server only with alchemistry and chemlib but it's the same.

Log: 
[17:37:19] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[17:37:20] [ForkJoinPool-1-worker-1/WARN]: Mod immersive_weathering uses the version 1.0.1-1.19_SNAPSHOT which isn't compatible with Loader's extended semantic version format (Invalid prerelease string '1.19_SNAPSHOT'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:37:20] [ForkJoinPool-1-worker-2/WARN]: Mod journeymap uses the version 5.9.0beta2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0beta2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:37:20] [main/INFO]: Dependencies overridden for fabric-api, cem, colormatic, debugify
[17:37:20] [main/WARN]: Warnings were found!
 - Mod 'Fabric API' (fabric-api) 0.59.0+1.19.2 recommends version latest of Fabulously Optimized, which is missing!
	 - You should install version latest of Fabulously Optimized for the optimal experience.
[17:37:20] [main/INFO]: Loading 118 mods:
	- alchemicaldrugs 1.0.0
	- alchemistry 1.0.1
	- architectury 6.1.39
	- badpackets 0.2.0
	- betteranimalsplus 1.19-11.0.7
	- blue_endless_jankson 1.2.1 via jankson
	- cardinal-components 5.0.1
	- cardinal-components-base 5.0.1 via cardinal-components
	- cardinal-components-block 5.0.1 via cardinal-components
	- cardinal-components-chunk 5.0.1 via cardinal-components
	- cardinal-components-entity 5.0.1 via cardinal-components
	- cardinal-components-item 5.0.1 via cardinal-components
	- cardinal-components-level 5.0.1 via cardinal-components
	- cardinal-components-scoreboard 5.0.1 via cardinal-components
	- cardinal-components-world 5.0.1 via cardinal-components
	- chemlib 1.0.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.69 via immersive_weathering
	- com_electronwill_night-config_core 3.6.5 via alchemistry
	- com_electronwill_night-config_toml 3.6.5 via alchemistry
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.12 via debugify
	- debugify 2.4.1
	- extraalchemy 1.8.3
	- fabric-api 0.59.0+1.19.2
	- fabric-api-base 0.4.10+e62f51a390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.8+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.16+83a8659290 via fabric-api
	- fabric-command-api-v1 1.2.10+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.6+0c17ea9690 via fabric-api
	- fabric-commands-v0 0.2.27+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.33+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.2+83a8659290 via fabric-api
	- fabric-convention-tags-v1 1.1.0+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.4+bd0a0d4a90 via fabric-api
	- fabric-data-generation-api-v1 5.1.7+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.29+a6d2f78590 via fabric-api
	- fabric-entity-events-v1 1.4.17+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.27+9ff28f4090 via fabric-api
	- fabric-events-lifecycle-v0 0.2.27+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.20+1899036190 via fabric-api
	- fabric-item-api-v1 1.5.6+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.27+6bee109e90 via fabric-api
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.1+83a8659290 via fabric-api
	- fabric-loot-api-v2 1.1.2+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.5+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.2+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.13+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.3+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.20+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.10+7675279690 via fabric-api
	- fabric-particles-v1 1.0.9+dc39553a90 via fabric-api
	- fabric-registry-sync-v0 0.9.23+23c4cfef90 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.13+9ff28f4090 via fabric-api
	- fabric-rendering-fluids-v1 3.0.6+9ff28f4090 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.10+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.0+6bee109e90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.12+9ff28f4090 via fabric-api
	- fabric-transfer-api-v1 2.0.10+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.2.0+1e232e1390 via fabric-api
	- fabricloader 0.14.9
	- farsight 1.19.1-2.0
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- forgeconfigapiport 4.1.4
	- geckolib3 3.1.13
	- iceberg 1.0.46
	- immersive_weathering 1.0.1-1.19_SNAPSHOT
	- inventorio 1.8.0
	- jankson 4.1.1+j1.2.1 via libgui
	- java 18
	- journeymap 5.9.0beta2
	- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT via journeymap
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- lazydfu 0.1.3
	- levelz 1.3.6
	- libgui 6.0.0-beta.5+1.19-pre1 via levelz
	- libninepatch 1.1.0 via libgui
	- lithium 0.8.3
	- magna 1.8.0-1.19 via modern_industrialization
	- megane 8.2.0
	- megane-api 8.2.0 via megane
	- megane-fabric-transfer 8.2.0 via megane
	- megane-reborn-energy 8.2.0 via megane
	- megane-runtime 8.2.0 via megane
	- megane-vanilla 8.2.0 via megane
	- memoryleakfix 1.19.1-0.7.0
	- minecraft 1.19.2
	- mixin-conflict-helper 1.1.0
	- modern_industrialization 1.3.2
	- mtmechs 1.0.14
	- nochatreports 1.19.2-v1.9.0
	- omega-config 1.0.8 via magna
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- patchouli 1.19-74-FABRIC
	- pehkui 3.4.0+1.14.4-1.19.2
	- playerabilitylib 1.6.0
	- roughlyenoughitems 9.1.524
	- simplylight 1.19-1.4.3
	- smoothboot 1.19-1.7.1
	- starlight 1.1.1+fabric.ae22326
	- team_reborn_energy 2.2.0 via alchemistry
	- travelersbackpack 1.19.1-8.1.1
	- trinkets 3.4.0
	- wthit 5.10.0
	- yosbr 0.1.1
[17:37:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Microsoft/Desktop/fabric%20serv/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:37:20] [main/INFO]: Compatibility level set to JAVA_17
[17:37:21] [main/INFO]: Preloading Debugify
[17:37:21] [main/INFO]: Done.
[17:37:21] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 1 override(s) found
[17:37:22] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[17:37:22] [main/INFO]: Smooth Boot config initialized
[17:37:24] [main/INFO]: Mixing server.MixinPlayer from nochatreports.mixins.json into net.minecraft.class_1657
[17:37:28] [main/INFO]: Building unoptimized datafixer
[17:37:31] [main/INFO]: Mixing server.MixinServerGamePacketListenerImpl from nochatreports.mixins.json into net.minecraft.class_3244
[17:37:31] [main/INFO]: Injecting super coyotes...
[17:37:31] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/23ca639241d73eaf919246602470f295
[17:37:31] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/d8f3c48219d933a6b2302c4d780df514
[17:37:31] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/dd94e2f3f0db361b8621d0f834adec1b
[17:37:31] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/59f1974289d63eb58cbd6fe813098096
[17:37:31] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/fd8d1482ead03ca8a9954263aa7f6289
[17:37:31] [main/INFO]: Overspawning lammergeiers...
[17:37:31] [main/INFO]: Saving config because the loaded bug fixes are different to stored json.
[17:37:31] [main/INFO]: Saving Debugify
[17:37:31] [main/INFO]: Enabled 2/35 bugs!
[17:37:31] [main/INFO]: Successfully Debugify'd your game!
[17:37:31] [main/INFO]: Registering pehkui effects
[17:37:31] [main/INFO]: Registered 16 status effects
[17:37:31] [main/INFO]: Registered dummy effects
[17:37:31] [main/INFO]: Registering pehkui potions
[17:37:31] [main/INFO]: Registered 39 potions
[17:37:31] [main/INFO]: Registering pehkui recipes
[17:37:32] [main/INFO]: farsight mod initialized
[17:37:32] [main/ERROR]: No data fixer registered for falling_icicle
[17:37:32] [main/ERROR]: No data fixer registered for falling_ash
[17:37:32] [main/ERROR]: No data fixer registered for falling_sand_layer
[17:37:32] [main/ERROR]: No data fixer registered for falling_leaf_layer
[17:37:32] [main/ERROR]: No data fixer registered for falling_propagule
[17:37:32] [main/INFO]: Initializing ServerSide Packet Registries
[17:37:33] [main/INFO]: Setting up Nuclear Items
[17:37:33] [main/INFO]: Modern Industrialization setup done!
[17:37:33] [main/INFO]: KONNICHIWA ZA WARUDO!
[17:37:33] [main/INFO]: Loading config...
[17:37:34] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[17:37:34] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[17:37:34] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[17:37:34] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[17:37:34] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[17:37:34] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[17:37:34] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[17:37:34] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[17:37:34] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[17:37:34] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[17:37:34] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[17:37:34] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[17:37:34] [main/INFO]: Registered the class com.tiviacz.travelersbackpack.fluids.effects.WaterEffect as a FluidEffect for minecraft:water 81000 with the ID 0
[17:37:34] [main/INFO]: Registered the class com.tiviacz.travelersbackpack.fluids.effects.LavaEffect as a FluidEffect for minecraft:lava 81000 with the ID 1
[17:37:34] [main/INFO]: Registered the class com.tiviacz.travelersbackpack.fluids.effects.PotionEffect as a FluidEffect for travelersbackpack:potion_still 27000 with the ID 2
[17:37:34] [main/INFO]: [WTHIT] Registering plugin modern_industrialization:plugin at aztech.modern_industrialization.compat.waila.MIWailaPlugin
[17:37:34] [main/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[17:37:34] [main/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[17:37:34] [main/INFO]: [WTHIT] Registering plugin levelz:plugin at net.levelz.waila.LevelWailaPlugin
[17:37:34] [main/INFO]: [WTHIT] Registering plugin megane:plugin at lol.bai.megane.runtime.Megane
[17:37:34] [main/INFO]: [megane] Loading lol.bai.megane.module.fabrictransfer.MeganeFabricTransfer from megane-fabric-transfer
[17:37:34] [main/INFO]: [megane] Loading lol.bai.megane.module.rebornenergy.MeganeRebornEnergy from megane-reborn-energy
[17:37:34] [main/INFO]: [megane] Loading lol.bai.megane.module.vanilla.MeganeVanilla from megane-vanilla
[17:37:34] [main/INFO]: [megane] Loading aztech.modern_industrialization.compat.megane.MIMeganeModule from modern_industrialization
[17:37:34] [main/INFO]: [WTHIT] Plugin config reloaded
[17:37:34] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'chemlib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
	at com.smashingmods.chemlib.registry.ItemRegistry.<clinit>(ItemRegistry.java:39) ~[ChemLib-1.19.2-1.0.0.jar:?]
	at com.smashingmods.chemlib.ChemLib.onInitialize(ChemLib.java:26) ~[ChemLib-1.19.2-1.0.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.smashingmods.chemlib.registry.ItemRegistry.<clinit>(ItemRegistry.java:39) ~[ChemLib-1.19.2-1.0.0.jar:?]
	at com.smashingmods.chemlib.ChemLib.onInitialize(ChemLib.java:26) ~[ChemLib-1.19.2-1.0.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
	... 7 more

**Comment by Dark-Arcana** [comment]
Hello! Please run your server again with only ChemLib and no other mods. When it crashes, please provide the crash report and latest log file. Don't copy/paste them into the issue. Use gist or pastebin to provide a link to the log contents. Thanks.

**Comment by Han3422** [comment]
Latest log: https://gist.github.com/Han3422/eca29d73dac39a88cc12f56e8fa5a15f

**Comment by Dark-Arcana** [comment]
Thank you. Looks like the issue is that the server is trying to load some client side only files. @TechnoVisionDev will need to take a look, but your information is helpful!

**Comment by Han3422** [comment]
Thanks to you for your hard work!

**Comment by TechnoVisionDev** [comment]
Thank you for the bug report @Han3422! I have just posted a hotfix on curseforge for ChemLib version 1.19.2-1.0.1 that should fix this issue. You can download it here: https://www.curseforge.com/minecraft/mc-mods/chemlib-fabric/files/3928813
 
It seems the periodic table of elements item was sharing a client-side class with the server.

**Comment by Han3422** [comment]
It works! Thanks
